# ==========================================
# CONFIGURACION DEL SERVIDOR DNS
# ==========================================
# No reenviar nombres sin puntos a los DNS externos
domain-needed

# No reenviar consultas de IPs privadas (búsquedas inversas) a internet
bogus-priv

# Evita por completo que dnsmasq use el archivo /etc/resolv.conf del host para salir a internet.
no-resolv

# Definir que este servidor es la autoridad única para el dominio local
local=/pucp.edu.pe/


# Registros DNS Estáticos
#address=/router.redes.local/172.16.10.1
address=/telecom.pucp.edu.pe/172.16.10.21
address=/redes.pucp.edu.pe/10.0.10.80

#address=/router.redes.local/::
address=/telecom.pucp.edu.pe/::
address=/redes.pucp.edu.pe/::

# Servidores DNS upstream (Permanecen comentados e inutilizados gracias a no-resolv)
#server=8.8.8.8
#server=1.1.1.1

# ==========================================
# CONFIGURACION DEL SERVIDOR DHCP
# ==========================================
dhcp-range=172.16.10.11,172.16.10.19,255.255.255.0,12h
dhcp-option=6,172.16.10.21
dhcp-option=3,172.16.10.21

# Habilitar filtro para evitar ruidos de IPv6 si lo deseas
filter-AAAA

# Habilitar el log detallado para verificar en la consola de Docker
log-dhcp
log-queries